### ISSUE TITLE
update_acme_tests fails (Post-CIME) to update test list

### ISSUE THREAD

**Issue by douglasjacobsen** [E3SM-Project/E3SM#334]
There are several issues with the update_acme_tests script that prevent it from working properly after CIME.

I don't know if this list is complete, but here are some of the issues.
1. The script fails to parse config_machines.xml, due to this line: https://github.com/ACME-Climate/ACME/blob/rljacob/acme-merge2/cime/machines-acme/config_machines.xml#L1637
2. The script can't find manage_xml_entries, because it no longer exists. @jnjohnsonlbl and I suspect it should be using https://github.com/ACME-Climate/ACME/blob/rljacob/acme-merge2/cime/scripts/manage_testlists instead, however...
3. The arguments passed in to manage_testlists, are incorrect...

Fixing the first two issues above, I get the following error:

```
└─▪ ./update_acme_tests ../scripts/testlist_allactive.xml acme_developer -p mustang,gnu
RUN: ../scripts/manage_testlists -removetests -category acme_developer -machine mustang -compiler gnu
  stat: 1

  output: Must supply a component argument via the -component option 
 values must be [allactive | cam | clm | cice | cism| drv | pop]

  errput: 

FAIL: Command: '../scripts/manage_testlists -removetests -category acme_developer -machine mustang -compiler gnu' failed with error ''
```
