### ISSUE TITLE
Crash while reading input files when using MPICH_GPU_SUPPORT_ENABLED=1 on Crusher

### ISSUE THREAD

**Issue by xyuan** [E3SM-Project/E3SM#5051]
The E3SM-MMF F case runs on Crusher occasionally crash with segmentation error(at every 3 to 5 runs) when reading the input NetCDF files using pNetCDF with MPICH_GPU_SUPPORT_ENABLED=1. However the runs do not crash when MPICH_GPU_SUPPORT_ENABLED is not set (MPICH_GPU_SUPPORT_ENABLED=0). See the detailed information below,

```
  0:  getMetaSchedule: tmpP:  13,  1,  12,  24,  11,  35,  146,  36,  1,  70,  147,  350,  3,  351,  2,  362,  113,  429
  0:  initializing elements...
  0: Create Pool
  0:
srun: error: crusher010: task 32: Segmentation fault (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=131056.0
  0: slurmstepd: error: *** STEP 131056.0 ON crusher005 CANCELLED AT 2022-06-20T16:05:47 ***
srun: error: crusher127: tasks 240-255: Terminated
srun: error: crusher008: tasks 16-31: Terminated
srun: error: crusher013: tasks 64-79: Terminated
srun: error: crusher016: tasks 96-111: Terminated
srun: error: crusher121: tasks 224-239: Terminated
srun: error: crusher017: tasks 112-127: Terminated
srun: error: crusher088: tasks 144-159: Terminated
srun: error: crusher005: tasks 0-15: Terminated
srun: error: crusher084: tasks 128-143: Terminated
srun: error: crusher102: tasks 192-207: Terminated
srun: error: crusher011: tasks 48-63: Terminated
srun: error: crusher091: tasks 160-175: Terminated
srun: error: crusher118: tasks 208-223: Terminated
srun: error: crusher098: tasks 176-191: Terminated
srun: error: crusher015: tasks 80-95: Terminated
srun: error: crusher010: tasks 33-47: Terminated
srun: Force Terminated StepId=131056.0
```

**back trace information from rockgdb gives the following call stack,**
```
#0  0x00007f9f3cba97ee in __cray_memcpy_ROME () from /opt/cray/pe/cce/14.0.0/cce/x86_64/lib/libu.so.1
#1  0x00007f9f445eae52 in ADIOI_R_Exchange_data_alltoallv.isra.0 () from /opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib/libmpi_cray.so.12
#2  0x00007f9f445ec114 in ADIOI_GPFS_ReadStridedColl () from /opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib/libmpi_cray.so.12
#3  0x00007f9f445d9400 in MPIOI_File_read_all () from /opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib/libmpi_cray.so.12
#4  0x00007f9f445daec1 in PMPI_File_read_at_all () from /opt/cray/pe/mpich/8.1.16/ofi/crayclang/10.0/lib/libmpi_cray.so.12
#5  0x00007f9f44b56734 in ncmpio_read_write () from /opt/cray/pe/parallel-netcdf/1.12.2.1/crayclang/10.0/lib/libpnetcdf_crayclang.so.4
#6  0x00007f9f44b51bea in wait_getput () from /opt/cray/pe/parallel-netcdf/1.12.2.1/crayclang/10.0/lib/libpnetcdf_crayclang.so.4
#7  0x00007f9f44b4edbd in ncmpio_wait () from /opt/cray/pe/parallel-netcdf/1.12.2.1/crayclang/10.0/lib/libpnetcdf_crayclang.so.4
#8  0x00007f9f44b5bb87 in ncmpio_get_varn () from /opt/cray/pe/parallel-netcdf/1.12.2.1/crayclang/10.0/lib/libpnetcdf_crayclang.so.4
#9  0x00007f9f44aca65a in ncmpi_get_varn_all () from /opt/cray/pe/parallel-netcdf/1.12.2.1/crayclang/10.0/lib/libpnetcdf_crayclang.so.4
#10 0x0000000002436ad9 in pio_read_darray_nc ()
#11 0x000000000243338b in PIOc_read_darray ()
#12 0x0000000002405314 in read_darray_internal_double$piodarray_ () at piodarray.F90:415
#13 0x0000000002405e7c in read_darray_3d_double$piodarray_ () at piodarray.F90:390
#14 0x0000000000e0f975 in infld_real_2d_3d$ncdio_atm_ () at ncdio_atm.F90:611
#15 0x000000000103c9b0 in read_inidat$inidat_ () at inidat.F90:32
#16 0x0000000000e12425 in initial_conds$startup_initialconds_ () at startup_initialconds.F90:54
#17 0x0000000000cc005d in cam_initial$inital_ () at inital.F90:63
#18 0x00000000005acbbd in cam_init$cam_comp_ () at cam_comp.F90:71
#19 0x0000000000594750 in atm_init_mct$atm_comp_mct_ () at atm_comp_mct.F90:106
#20 0x0000000000452055 in component_init_cc$component_mod_ () at component_mod.F90:190
#21 0x0000000000425673 in cime_init$cime_comp_mod_ () at cime_comp_mod.F90:1383
#22 0x000000000044ffa3 in main () at cime_driver.F90:122
```
