### ISSUE TITLE
add a concurrency check to gh workflows

### ISSUE THREAD

**Issue by mahf708** [E3SM-Project/E3SM#6652]
And maybe I would also add a concurrency check. If a commit is pushed while testing, we should kill any other existing PR. Something like

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true
```

Btw, I'm not sure why we would want a workflow_dispath trigger here. And if you removed "workflow_dispatch", the group could simply be `${{ github.workflow }}-${{ github.event.pull_request.number}}`. But I don't feel strongly about this, so I'm ok keeping workflow_dispatch.

_Originally posted by @bartgol in https://github.com/E3SM-Project/E3SM/pull/6637#discussion_r1771779380_
